# Generated by Django 3.1.7 on 2021-04-16 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upcoming_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='course name')),
                ('date_announced', models.DateTimeField(verbose_name='date announced')),
                ('test_time', models.DateTimeField(verbose_name='test time')),
                ('venue', models.CharField(max_length=50, verbose_name='venue')),
                ('area_of_concentration', models.CharField(max_length=50, verbose_name='area of concentration')),
                ('test_marks', models.CharField(max_length=50, verbose_name='test marks')),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.group', verbose_name='group id')),
            ],
        ),
        migrations.CreateModel(
            name='pending_assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='course name')),
                ('assignment_question', models.CharField(max_length=5000, verbose_name='assignment question')),
                ('related_file_for_assignment', models.FileField(blank=True, max_length=30, null=True, upload_to='media')),
                ('submitted_to_who', models.CharField(max_length=50, verbose_name='to be submitted to whom')),
                ('where_to_submit', models.CharField(max_length=50, verbose_name='where  to submit')),
                ('assignment_marks', models.CharField(max_length=50, verbose_name='marks the assignment will take')),
                ('assignment_dueDate', models.DateTimeField(verbose_name='assignment due date')),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.group', verbose_name='group id')),
            ],
        ),
        migrations.CreateModel(
            name='lecture_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=25, verbose_name='Course name')),
                ('course_code', models.CharField(max_length=10, verbose_name='course code')),
                ('venue', models.CharField(max_length=50, verbose_name='venue')),
                ('time_start', models.DateTimeField(verbose_name='lecture starting time')),
                ('time_end', models.DateTimeField(verbose_name='lecture finish time')),
                ('course_topic', models.CharField(max_length=50, verbose_name='course topic')),
                ('lecture_requirement', models.CharField(max_length=100, verbose_name='lecture requirement')),
                ('attendance', models.BooleanField(default=True, verbose_name='will attendance be taken')),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
            ],
        ),
        migrations.CreateModel(
            name='important_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('body', models.CharField(max_length=5000, verbose_name='body')),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
            ],
        ),
    ]
